[package]
name = "bili_api_http"
version = "0.1.0"
authors = ["sivrw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
serde_json = "1.0.63"
reqwest = {version = "0.11.0", features = ["blocking"]}